import fs from 'fs';
import path from 'path';
import Module from './wasm-models/LotA-model/edge-impulse-standalone.js';


// This is the WASM model file generated by Edge Impulse

// Load image (or CSV data if you're using raw features)
const inputFeatures =[0.15, 0.62, 0.04, 0.91, 0.38, 0.47];

(async () => {
    console.log("Loading WASM model...");

    const classifier = await Module;

    const result = classifier.classify(inputFeatures);
    console.log("✅ Classification result:", result);

})().catch(err => {
    console.error("❌ Error running classifier:", err);
});
